/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Estrella
 */
public class Catalago extends javax.swing.JFrame {

    /**
     * Creates new form Catalago
     */
    public Catalago() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FIRSTSCOPE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EQ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        NEXSTAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TELESCOPIO FIRSTSCOPE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FIRTSCOPE.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        FIRSTSCOPE.setBackground(new java.awt.Color(0, 0, 0));
        FIRSTSCOPE.setForeground(new java.awt.Color(255, 255, 255));
        FIRSTSCOPE.setText("VER DESCRIPCION ");
        FIRSTSCOPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRSTSCOPEActionPerformed(evt);
            }
        });
        getContentPane().add(FIRSTSCOPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 172, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 2, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TELESCOPIO CELESTRON ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ASTROMASTER LT 70AZ REFACTOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CELESTRON ASTROMASTER LT 70AZ - REFRACTOR.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 173, 191));

        LT.setBackground(new java.awt.Color(0, 0, 0));
        LT.setForeground(new java.awt.Color(255, 255, 255));
        LT.setText("VER DESCRIPCION");
        LT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LTActionPerformed(evt);
            }
        });
        getContentPane().add(LT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 173, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TELESCOPIO CELESTRON ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ASTROMASTER 130 EQ MD NEWTONIANO  ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/130 EQ (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        EQ.setBackground(new java.awt.Color(0, 0, 0));
        EQ.setForeground(new java.awt.Color(255, 255, 255));
        EQ.setText("VER DESCRIPCION ");
        EQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EQActionPerformed(evt);
            }
        });
        getContentPane().add(EQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 177, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELESCOPIO CELESTRON ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NEXSTAR 5SE COMPUTARIZADO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NexStar.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 180, 180));

        NEXSTAR.setBackground(new java.awt.Color(0, 0, 0));
        NEXSTAR.setForeground(new java.awt.Color(255, 255, 255));
        NEXSTAR.setText("VER DESCRIPCION ");
        NEXSTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXSTARActionPerformed(evt);
            }
        });
        getContentPane().add(NEXSTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 186, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FF.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 630));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SCHMIDT CASSEGRAIN ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 345, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FIRSTSCOPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRSTSCOPEActionPerformed
        JOptionPane.showMessageDialog(null, "Precio:3,650 Lps \n" 
                                          + "Garantía: 2 años.\n" + 
                                          "1-Liviano y portátil, un excelente telescopio de mesa.\n" +
                                          "2-Su diseño simple lo convierte en un perfecto equipo para los que se quieren iniciar en la Astronomía.\n" +
                                          "3-No se requiere de herramientas para su armado.\n" +
                                          "4-Incluye un apuntador, 2 Oculares del tipo Kellner y una aplicación de planetario gratis."
                                        + "\n"+"Especificaciones Técnicas:"
                                        + "\n" +"Tipo de Telescopio: Newtoniano Reflector "
                                        + "\n" +"Apertura: 76mm (2,99 pulgadas)\n" 
                                        + "Distancia Focal: 300mm\n" 
                                        + "Relación focal: f/3.95");
    }//GEN-LAST:event_FIRSTSCOPEActionPerformed

    private void LTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LTActionPerformed
        JOptionPane.showMessageDialog(null,"Precio:8,225 \n"
                                         + "Garantia: 2 años\n"
                                         + "Caracteristicas:\n"
                                         + "1-No requiere de herramientas para su armado \n"
                                         + "2-Incluye dos poderosos oculares, uno de 20 mm (35x) y otro de 10 mm (70x)\n"
                                         + "3-Amplia apertura de 70mm para una máxima recolección de luz \n"
                                         + "4-Trípode resistente de acero \n"
                                         + "Especificación Técnica:\n"
                                         + "Tipo de Telescopio:\n"
                                         + "RefractorApertura: 70mm (2,76 pulgadas)\n"
                                         + "Distancia Focal: 700mm\n"
                                         + "Relación focal: f/10 \n"
                                         + "Máximo aumento útil: 165x\n"
                                         + "Poder de captación de luz: 100x (comparado con el ojo humano)");
        
    }//GEN-LAST:event_LTActionPerformed

    private void EQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EQActionPerformed
        JOptionPane.showMessageDialog(null,"Precio: 22789.92 \n"
                                         +"Garantia: 2 años"
                                         +"Caracteristicas: \n"
                                         +"1-No requiere herramientas para su armado.\n"
                                         +"2-Apuntador de estrellas montado permanentemente.\n" 
                                         +"3-Para observaciones terrestres y astronómicas\n" 
                                         +"4-Liberación rápida del tubo óptico.\n" 
                                         +"5-Montura ecuatorial alemana con ajustadores circulares \n para una precisa localización y seguimiento de objetos celestes.\n" 
                                         +"6-La montura posee un motor para el seguimiento automático \n de cuerpos celestes.\n" 
                                         +"7-Trípode recubierto de goma con patas de acero de 1.25'', \n provee una rígida y estable observación.\n" 
                                         +"8-Espejos recubiertos para una clara y nítida imagen.\n" 
                                         +"9-Porta accesorios para guardar oculares.\n" 
                                         +"10-Incluye dos poderosos oculares, uno de 20 mm (33x) y otro de 10 mm (65x). \n "
                                         + "Especificaciones Técnicas:\n" 
                                         +"Tipo de Telescopio: Newtoniano Reflector\n" 
                                         +"Apertura: 130mm (5,12 pulgadas)\n" 
                                         +"Distancia Focal: 650mm\n"
                                         +"Relación focal: f/5");
    }//GEN-LAST:event_EQActionPerformed

    private void NEXSTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXSTARActionPerformed
        JOptionPane.showMessageDialog(null,"Precio: 36298.66 \n Telescopio Schmidt-Cassegrain de 5 pulgadas \n ópticas recubiertas StarBright XLT de alta transmisión.\n" 
                                         +"Garantia:2años \n"
                                         +"Caracteristicas:\n"
                                         +"1-Apuntador de estrellas para ayudar a alinear y ubicar con precisión los objetos.\n" 
                                         +"-2Montura de rápida liberación, tubo óptico, y compartimiento para oculares. \n No requiere de herramientas para su armado.\n" 
                                         +"3-El sistema SkyAlign te permite alinear con cualquier objeto celeste brillante.\n" 
                                         +"4-Dispone de una Base de Datos de 40.000 objetos celestes con espacio para 200 objetos. \n Además contiene información detallada de casi 200 objetos celestes.\n" 
                                         +"5-Batería Interna para realizar observaciones sin la necesidad de energía eléctrica.\n"
                                         +"6-Incluye un poderoso ocular de 25 mm (50x).\n"
                                         +"Especificaciones Técnicas:\n" 
                                         +"Tipo de Telescopio: Schmidt-Cassegrain\n" 
                                         +"Apertura: 125mm (5 pulgadas)\n" 
                                         +"Distancia Focal: 1250 mm\n"
                                         +"Relación focal: f/10");
    }//GEN-LAST:event_NEXSTARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Parte3 P3= new Parte3();
       P3.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EQ;
    private javax.swing.JButton FIRSTSCOPE;
    private javax.swing.JButton LT;
    private javax.swing.JButton NEXSTAR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
