/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Estrella
 */
public class Facturas extends javax.swing.JFrame {
        DefaultTableModel modelo= new DefaultTableModel();
        
    /**
     * Creates new form Facturas
     */
    public Facturas() {
        initComponents();
        this.setLocationRelativeTo(null);
       
        modelo.addColumn("Producto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Importe");
        this.jTable1.setModel(modelo);
    }
    public Image getIconImage(){
        Image retValue =Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        RegresaraParte3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        producto = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        unitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        impuesto = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminarpro = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eliminartodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 80, -1));

        RegresaraParte3.setBackground(new java.awt.Color(0, 0, 0));
        RegresaraParte3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegresaraParte3.setForeground(new java.awt.Color(255, 255, 255));
        RegresaraParte3.setText("REGRESAR");
        RegresaraParte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresaraParte3ActionPerformed(evt);
            }
        });
        getContentPane().add(RegresaraParte3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ASTROSHOP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FACTURA ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 80, 20));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 270));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("F001-000001234");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Poducto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, -1));

        producto.setBackground(new java.awt.Color(0, 0, 0));
        producto.setForeground(new java.awt.Color(255, 255, 255));
        producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRSTSCOPE Telescopio", "LT70 AZ", "Telescopio 130EQ", "NEXSTAR" }));
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, -1));
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 160, -1));
        getContentPane().add(unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio unitario");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 100, 30));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SUBTOTAL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));
        getContentPane().add(impuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 100, 30));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 30));

        agregar.setBackground(new java.awt.Color(0, 0, 0));
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 90, 30));

        eliminarpro.setBackground(new java.awt.Color(0, 0, 0));
        eliminarpro.setForeground(new java.awt.Color(255, 255, 255));
        eliminarpro.setText("ELIMINAR PRODUCTO ");
        eliminarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarproActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("I.S.V 15%");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));

        eliminartodo.setBackground(new java.awt.Color(0, 0, 0));
        eliminartodo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        eliminartodo.setForeground(new java.awt.Color(255, 255, 255));
        eliminartodo.setText("ELIMINAR TODO");
        eliminartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminartodoActionPerformed(evt);
            }
        });
        getContentPane().add(eliminartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FF.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 540, 622));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegresaraParte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresaraParte3ActionPerformed
        Parte3 p3=new Parte3();
        p3.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_RegresaraParte3ActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
       
        String pre="";
      
           switch(producto.getSelectedIndex()){
               case 0:pre="3650";break;
               case 1:pre="22789.92";break;
               case 2:pre="8225";break;
               case 3:pre="36298.66";break;
               
               
              
               
           }
           unitario.setText(pre);
           cantidad.setText("1");
           
           
       
    }//GEN-LAST:event_productoActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        String rowData[]=new String[4];
        rowData[0]=producto.getSelectedItem().toString();
        rowData[1]=unitario.getText();
        rowData[2]=cantidad.getText();
        Double imp=Double.parseDouble(rowData[1])*Double.parseDouble(rowData[2]);
        imp=redondear(imp);
        rowData[3]=imp.toString();
        modelo.addRow(rowData);
        calTot();
 
        cantidad.setText("");
        unitario.setText("");
        
        
    }//GEN-LAST:event_agregarActionPerformed

    private void eliminarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarproActionPerformed
       int fila=jTable1.getSelectedRow();
        if(fila>=0){
            modelo.removeRow(fila);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccionar fila");
        }
    }//GEN-LAST:event_eliminarproActionPerformed

    private void eliminartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminartodoActionPerformed
          int fila=jTable1.getRowCount();
        for(int  i=fila-1; i>=0; i--){
            modelo.removeRow(i);
            impuesto.setText("");
            subtotal.setText("");
            total.setText("");
            cliente.setText("");
           
       }     
    }//GEN-LAST:event_eliminartodoActionPerformed
    private double redondear (double num){
        return Math.rint(num*100)/100;
    }
    private void calTot(){
        double S=0,isv,tot;
        for(int i=0;i<jTable1.getRowCount();i++){
                S=S+Double.parseDouble(modelo.getValueAt(i, 3).toString());
            }
            S=redondear(S);
            subtotal.setText(String.valueOf(S));
            isv=0.15*S;
            isv=redondear(isv);
            tot=S*1.15;
            tot=redondear(tot);
            impuesto.setText(String.valueOf(isv));
            total.setText(String.valueOf(tot));
            }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegresaraParte3;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cliente;
    private javax.swing.JButton eliminarpro;
    private javax.swing.JButton eliminartodo;
    private javax.swing.JTextField impuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> producto;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField unitario;
    // End of variables declaration//GEN-END:variables
}
